name: Build Vili Kernel (KSU-Next v3)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/moha998844/from-lisa-24-02-26
          kernel-branch: lineage-23.2
          config: vili_defconfig
          arch: arm64
          aosp-clang: false
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz
          other-clang-branch: main
         # Add this line below to fix the error
          aosp-gcc: true
 
   # KernelSU-Next Legacy for 5.4 Xiaomi Kernels
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/rifsxd/KernelSU-Next
          ksu-version: legacy

          # Toolchain Setup (Bypassing Error 400)
          aosp-clang: false
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz
          other-clang-branch: main
          aosp-gcc: true

          extra-make-args: >-
            ["LLVM=1", "LLVM_IAS=1", "dtbs",
            "CONFIG_CC_OPTIMIZE_03=y",
            "CONFIG_SCHED_WALT=y",
            "CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y",
            "CONFIG_WIREGUARD=y",
            "CONFIG_QCOM_RPMH=y",
            "CONFIG_REGULATOR_QCOM_RPMH=y",
            "CONFIG_SECURITY_SELINUX=y",
            "CONFIG_LTO_CLANG_THIN=y",
            "CONFIG_KSU=y",
            "CONFIG_KSU_NEXT=y",
            "CONFIG_KPROBES=n",
            "CONFIG_HAVE_KPROBES=y",
            "CONFIG_KPROBE_EVENTS=y"]
          anykernel3: true
